### ISSUE TITLE
Poly FM: Respecifying to fewer timbres works, but throws an error

### ISSUE THREAD

**Issue by tyhodson** [expertsleepersltd/distingNT#4]
Hi os,

Firmware v1.4.0

If I load Poly FM from scratch with any number of timbres specified, and then respecify to fewer timbres, I get the error below. The thing is, it actually does successfully respec down.

![PolyFM_respec-timbres-down-error](https://github.com/user-attachments/assets/a20ac6f4-8c4d-481c-9b14-cb0a08dae16b)

This error only occurs when I spec down timbres. I can spec down voices with no error, and I can spec up timbres and voices with no error.

The attached preset is with a freshly loaded Poly FM with 2 timbres specified. After saving this preset, I respecified to 1 timbre and confirmed I could repro the error.
[Poly FM test.json.zip](https://github.com/user-attachments/files/18090512/Poly.FM.test.json.zip)

P.S. I haven't tested this with every other algorithm that has timbres, but I do see the same situation with Poly Multisample.

Thanks!
ty

**Comment by tyhodson** [comment]
P.S. I haven't tested this with every other algorithm that has timbres, but I do see the same situation with Poly Multisample.

**Comment by expertsleepers** [comment]
Thanks, confirmed and fixed. Please test in the next 1.5beta.

**Comment by expertsleepers** [comment]
You can test this in https://discord.com/channels/1268195809502036049/1292493724462485647/1316721286839402526

**Comment by tyhodson** [comment]
That fixed it -- thanks!
